### ISSUE TITLE
App crashing if not connected to internet

### ISSUE THREAD

**Issue by appteam-nith** [appteam-nith/festnimbus#17]
FATAL EXCEPTION: main
                                                                    Process: com.appteam.nimbus, PID: 26633
                                                                    java.lang.NullPointerException: Attempt to read from field 'int com.android.volley.NetworkResponse.statusCode' on a null object reference
                                                                        at com.appteam.nimbus.Login$4.onErrorResponse(Login.java:105)
                                                                        at com.android.volley.Request.deliverError(Request.java:598)
                                                                        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by nishant23j** [comment]
done on the login part !! 
Can anyone tell me who was working on register.java ??
